allowBuilds:
  esbuild: true
  tree-sitter-javascript: false
  tree-sitter-python: false
  tree-sitter-typescript: false

minimumReleaseAgeExclude:
  - "@guillaume-docquier/tools-ts"

strictPeerDependencies: true
