allowBuilds:
  esbuild: true
  tree-sitter-javascript: false
  tree-sitter-python: false
  tree-sitter-typescript: false

minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@guillaume-docquier/tools-ts"
  - "@guillaume-docquier/oxfmt"
  - "@guillaume-docquier/oxlint"

strictPeerDependencies: true
